baseURL = "https://meolv.github.io/all101lang/"
locale = "uk"
title = "101-мовний осередок"
theme = "ananke"

defaultContentLanguage = "uk"
defaultContentLanguageInSubdir = true

[params]
  disable_language_toggle = true

[languages]
  [languages.uk]
    locale = "uk"
    label = "Українська"
    title = "101-мовний осередок"
    weight = 1
  [languages."af"]
    locale = "af"
    label = "Afrikaans"
    title = "101 Languages Hub"
    weight = 2
  [languages."am"]
    locale = "am"
    label = "አማርኛ"
    title = "101 Languages Hub"
    weight = 3
  [languages."ar"]
    locale = "ar"
    label = "العربية"
    title = "101 Languages Hub"
    weight = 4
  [languages."az"]
    locale = "az"
    label = "Azərbaycan"
    title = "101 Languages Hub"
    weight = 5
  [languages."bg"]
    locale = "bg"
    label = "Български"
    title = "101 Languages Hub"
    weight = 6
  [languages."bn"]
    locale = "bn"
    label = "বাংলা"
    title = "101 Languages Hub"
    weight = 7
  [languages."bs"]
    locale = "bs"
    label = "Bosanski"
    title = "101 Languages Hub"
    weight = 8
  [languages."ca"]
    locale = "ca"
    label = "Català"
    title = "101 Languages Hub"
    weight = 9
  [languages."ceb"]
    locale = "ceb"
    label = "Cebuan"
    title = "101 Languages Hub"
    weight = 10
  [languages."co"]
    locale = "co"
    label = "Corsu"
    title = "101 Languages Hub"
    weight = 11
  [languages."cs"]
    locale = "cs"
    label = "Čeština"
    title = "101 Languages Hub"
    weight = 12
  [languages."cy"]
    locale = "cy"
    label = "Cymraeg"
    title = "101 Languages Hub"
    weight = 13
  [languages."da"]
    locale = "da"
    label = "Dansk"
    title = "101 Languages Hub"
    weight = 14
  [languages."de"]
    locale = "de"
    label = "Deutsch"
    title = "101 Languages Hub"
    weight = 15
  [languages."el"]
    locale = "el"
    label = "Ελληνικά"
    title = "101 Languages Hub"
    weight = 16
  [languages."en"]
    locale = "en"
    label = "English"
    title = "101 Languages Hub"
    weight = 17
  [languages."eo"]
    locale = "eo"
    label = "Esperanto"
    title = "101 Languages Hub"
    weight = 18
  [languages."es"]
    locale = "es"
    label = "Español"
    title = "101 Languages Hub"
    weight = 19
  [languages."et"]
    locale = "et"
    label = "Eesti"
    title = "101 Languages Hub"
    weight = 20
  [languages."eu"]
    locale = "eu"
    label = "Euskara"
    title = "101 Languages Hub"
    weight = 21
  [languages."fa"]
    locale = "fa"
    label = "فارسی"
    title = "101 Languages Hub"
    weight = 22
  [languages."fi"]
    locale = "fi"
    label = "Suomi"
    title = "101 Languages Hub"
    weight = 23
  [languages."fr"]
    locale = "fr"
    label = "Français"
    title = "101 Languages Hub"
    weight = 24
  [languages."fy"]
    locale = "fy"
    label = "Frysk"
    title = "101 Languages Hub"
    weight = 25
  [languages."ga"]
    locale = "ga"
    label = "Gaeilge"
    title = "101 Languages Hub"
    weight = 26
  [languages."gd"]
    locale = "gd"
    label = "Gàidhlig"
    title = "101 Languages Hub"
    weight = 27
  [languages."gl"]
    locale = "gl"
    label = "Galego"
    title = "101 Languages Hub"
    weight = 28
  [languages."gu"]
    locale = "gu"
    label = "ગુજરાતી"
    title = "101 Languages Hub"
    weight = 29
  [languages."ha"]
    locale = "ha"
    label = "Hausa"
    title = "101 Languages Hub"
    weight = 30
  [languages."haw"]
    locale = "haw"
    label = "ʻŌlelo Hawaiʻi"
    title = "101 Languages Hub"
    weight = 31
  [languages."hi"]
    locale = "hi"
    label = "हिन्दी"
    title = "101 Languages Hub"
    weight = 32
  [languages."hmn"]
    locale = "hmn"
    label = "Hmoob"
    title = "101 Languages Hub"
    weight = 33
  [languages."hr"]
    locale = "hr"
    label = "Hrvatski"
    title = "101 Languages Hub"
    weight = 34
  [languages."ht"]
    locale = "ht"
    label = "Kreyòl ayisyen"
    title = "101 Languages Hub"
    weight = 35
  [languages."hu"]
    locale = "hu"
    label = "Magyar"
    title = "101 Languages Hub"
    weight = 36
  [languages."hy"]
    locale = "hy"
    label = "Հայերեն"
    title = "101 Languages Hub"
    weight = 37
  [languages."id"]
    locale = "id"
    label = "Bahasa Indonesia"
    title = "101 Languages Hub"
    weight = 38
  [languages."ig"]
    locale = "ig"
    label = "Asụsụ Igbo"
    title = "101 Languages Hub"
    weight = 39
  [languages."is"]
    locale = "is"
    label = "Íslenska"
    title = "101 Languages Hub"
    weight = 40
  [languages."it"]
    locale = "it"
    label = "Italiano"
    title = "101 Languages Hub"
    weight = 41
  [languages."iw"]
    locale = "iw"
    label = "עברית"
    title = "101 Languages Hub"
    weight = 42
  [languages."ja"]
    locale = "ja"
    label = "日本語"
    title = "101 Languages Hub"
    weight = 43
  [languages."jw"]
    locale = "jw"
    label = "Basa Jawa"
    title = "101 Languages Hub"
    weight = 44
  [languages."ka"]
    locale = "ka"
    label = "ქართული"
    title = "101 Languages Hub"
    weight = 45
  [languages."kk"]
    locale = "kk"
    label = "Қазақ тілі"
    title = "101 Languages Hub"
    weight = 46
  [languages."km"]
    locale = "km"
    label = "ភាសាខ្មែរ"
    title = "101 Languages Hub"
    weight = 47
  [languages."kn"]
    locale = "kn"
    label = "ಕನ್ನಡ"
    title = "101 Languages Hub"
    weight = 48
  [languages."ko"]
    locale = "ko"
    label = "한국어"
    title = "101 Languages Hub"
    weight = 49
  [languages."ku"]
    locale = "ku"
    label = "Kurdî"
    title = "101 Languages Hub"
    weight = 50
  [languages."ky"]
    locale = "ky"
    label = "Kırgızça"
    title = "101 Languages Hub"
    weight = 51
  [languages."la"]
    locale = "la"
    label = "Latina"
    title = "101 Languages Hub"
    weight = 52
  [languages."lb"]
    locale = "lb"
    label = "Lëtzebuergesch"
    title = "101 Languages Hub"
    weight = 53
  [languages."lo"]
    locale = "lo"
    label = "ພາສາລາວ"
    title = "101 Languages Hub"
    weight = 54
  [languages."lt"]
    locale = "lt"
    label = "Lietuvių"
    title = "101 Languages Hub"
    weight = 55
  [languages."lv"]
    locale = "lv"
    label = "Latviešu"
    title = "101 Languages Hub"
    weight = 56
  [languages."mg"]
    locale = "mg"
    label = "Malagasy"
    title = "101 Languages Hub"
    weight = 57
  [languages."mi"]
    locale = "mi"
    label = "Māori"
    title = "101 Languages Hub"
    weight = 58
  [languages."mk"]
    locale = "mk"
    label = "Македонски"
    title = "101 Languages Hub"
    weight = 59
  [languages."ml"]
    locale = "ml"
    label = "മലയാളം"
    title = "101 Languages Hub"
    weight = 60
  [languages."mn"]
    locale = "mn"
    label = "Монгол"
    title = "101 Languages Hub"
    weight = 61
  [languages."mr"]
    locale = "mr"
    label = "मराठी"
    title = "101 Languages Hub"
    weight = 62
  [languages."ms"]
    locale = "ms"
    label = "Bahasa Melayu"
    title = "101 Languages Hub"
    weight = 63
  [languages."mt"]
    locale = "mt"
    label = "Malti"
    title = "101 Languages Hub"
    weight = 64
  [languages."my"]
    locale = "my"
    label = "မြန်မာစာ"
    title = "101 Languages Hub"
    weight = 65
  [languages."ne"]
    locale = "ne"
    label = "नेपाली"
    title = "101 Languages Hub"
    weight = 66
  [languages."nl"]
    locale = "nl"
    label = "Nederlands"
    title = "101 Languages Hub"
    weight = 67
  [languages."no"]
    locale = "no"
    label = "Norsk"
    title = "101 Languages Hub"
    weight = 68
  [languages."ny"]
    locale = "ny"
    label = "Chichewa"
    title = "101 Languages Hub"
    weight = 69
  [languages."pa"]
    locale = "pa"
    label = "ਪੰਜਾਬੀ"
    title = "101 Languages Hub"
    weight = 70
  [languages."pl"]
    locale = "pl"
    label = "Polski"
    title = "101 Languages Hub"
    weight = 71
  [languages."ps"]
    locale = "ps"
    label = "پښتو"
    title = "101 Languages Hub"
    weight = 72
  [languages."pt"]
    locale = "pt"
    label = "Português"
    title = "101 Languages Hub"
    weight = 73
  [languages."ro"]
    locale = "ro"
    label = "Română"
    title = "101 Languages Hub"
    weight = 74
  [languages."sd"]
    locale = "sd"
    label = "سنڌي"
    title = "101 Languages Hub"
    weight = 75
  [languages."si"]
    locale = "si"
    label = "සිංහල"
    title = "101 Languages Hub"
    weight = 76
  [languages."sk"]
    locale = "sk"
    label = "Slovenčina"
    title = "101 Languages Hub"
    weight = 77
  [languages."sl"]
    locale = "sl"
    label = "Slovenščina"
    title = "101 Languages Hub"
    weight = 78
  [languages."sm"]
    locale = "sm"
    label = "Gagana Sāmoa"
    title = "101 Languages Hub"
    weight = 79
  [languages."sn"]
    locale = "sn"
    label = "Chishona"
    title = "101 Languages Hub"
    weight = 80
  [languages."so"]
    locale = "so"
    label = "Soomaali"
    title = "101 Languages Hub"
    weight = 81
  [languages."sq"]
    locale = "sq"
    label = "Shqip"
    title = "101 Languages Hub"
    weight = 82
  [languages."sr"]
    locale = "sr"
    label = "Српски"
    title = "101 Languages Hub"
    weight = 83
  [languages."st"]
    locale = "st"
    label = "Sesotho"
    title = "101 Languages Hub"
    weight = 84
  [languages."su"]
    locale = "su"
    label = "Basa Sunda"
    title = "101 Languages Hub"
    weight = 85
  [languages."sv"]
    locale = "sv"
    label = "Svenska"
    title = "101 Languages Hub"
    weight = 86
  [languages."sw"]
    locale = "sw"
    label = "Kiswahili"
    title = "101 Languages Hub"
    weight = 87
  [languages."ta"]
    locale = "ta"
    label = "தமிழ்"
    title = "101 Languages Hub"
    weight = 88
  [languages."te"]
    locale = "te"
    label = "తెలుగు"
    title = "101 Languages Hub"
    weight = 89
  [languages."tg"]
    locale = "tg"
    label = "Тоҷикӣ"
    title = "101 Languages Hub"
    weight = 90
  [languages."th"]
    locale = "th"
    label = "ไทย"
    title = "101 Languages Hub"
    weight = 91
  [languages."tl"]
    locale = "tl"
    label = "Tagalog"
    title = "101 Languages Hub"
    weight = 92
  [languages."tr"]
    locale = "tr"
    label = "Türkçe"
    title = "101 Languages Hub"
    weight = 93
  [languages."ur"]
    locale = "ur"
    label = "اردو"
    title = "101 Languages Hub"
    weight = 94
  [languages."uz"]
    locale = "uz"
    label = "Oʻzbekcha"
    title = "101 Languages Hub"
    weight = 95
  [languages."vi"]
    locale = "vi"
    label = "Tiếng Việt"
    title = "101 Languages Hub"
    weight = 96
  [languages."xh"]
    locale = "xh"
    label = "isiXhosa"
    title = "101 Languages Hub"
    weight = 97
  [languages."yi"]
    locale = "yi"
    label = "ייִדיש"
    title = "101 Languages Hub"
    weight = 98
  [languages."yo"]
    locale = "yo"
    label = "Èdè Yorùbá"
    title = "101 Languages Hub"
    weight = 99
  [languages."zh-CN"]
    locale = "zh-CN"
    label = "简体中文"
    title = "101 Languages Hub"
    weight = 100
  [languages."zh-TW"]
    locale = "zh-TW"
    label = "繁體中文"
    title = "101 Languages Hub"
    weight = 101
  [languages."zu"]
    locale = "zu"
    label = "isiZulu"
    title = "101 Languages Hub"
    weight = 102

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
